### ISSUE TITLE
Kodi Update -> Matrix - errors with API

### ISSUE THREAD

**Issue by luchmhor** [s0faking/plugin.video.orftvthek#102]
After the upgrade to Kodi v19 (v0.12 of plugin) get the following error, it does not seem to related to already solved API errors reported:

```
2021-05-03 20:33:57.232 T:2956     INFO <general>: initializing python engine.
2021-05-03 20:33:59.338 T:2956    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: not all arguments converted during string formatting
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.orftvthek/default.py", line 6, in <module>
                                                       Addon.run()
                                                     File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/Addon.py", line 169, in run
                                                       scraper.getSchedule()
                                                     File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/ServiceApi.py", line 268, in getSchedule
                                                       title = '$s %s' % (self.translation(30064), title)
                                                   TypeError: not all arguments converted during string formatting
                                                   -->End of Python script error report<--
                                                   
2021-05-03 20:33:59.688 T:2956     INFO <general>: Python interpreter stopped
2021-05-03 20:33:59.708 T:2955    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getSchedule
2021-05-03 20:33:59.736 T:2673    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getSchedule) failed
```

**Comment by jaylinski** [comment]
Same error for me on matrix.

**Comment by s0faking** [comment]
this was caused by a dirty typo ;). please try 0.12.1 from the release page.

**Comment by luchmhor** [comment]
thx for the quick fix, works again
