### ISSUE TITLE
Anzeige des Datums im Addon

### ISSUE THREAD

**Issue by m3ltd0wn** [s0faking/plugin.video.orftvthek#123]
Da ich gerade LibreELEC neu installiert habe, weiß ich nicht an was genau es liegt, aber mit der derzeitigen Konfiguration wird mir das Datum der jeweiligen Sendung nicht mehr angezeigt. Im Addon selber kann man da ja vermutlich nichts umstellen ... würd mich sehr über 'nen Tipp freuen!

**Comment by killerbees19** [comment]
Hast Du in der Addon-Konfiguration die Service-API aktiviert oder ist sie inaktiv? Afaik macht das nämlich genau bei solchen Dingen einen Unterschied, ob das Ausstrahlungsdatum direkt sichtbar ist.

Ansonsten: Welches Skin verwendet LibreELEC? Bei manchen Skins kann man in den Einstellungen relativ viel umkonfigurieren.

**Comment by m3ltd0wn** [comment]
ServiceAPI ist aktiviert - ist sie deaktiviert ist (zumindest bei mir) das ganze Addon unbrauchbar:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: Module <module 'xbmcvfs' (built-in)> does not have attribute "translatePath"!
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 6, in <module>
                                                Addon.run()
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/Addon.py", line 135, in run
                                                scraper.getCategories()
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/HtmlScraper.py", line 321, in getCategories
                                                self.html2ListItem(title, image, "", desc, "", "", "", url)
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/HtmlScraper.py", line 577, in html2ListItem
                                                return createListItem(title, banner, description, duration, date, channel, videourl, playable, folder, backdrop, self.pluginhandle, subtitles, blacklist, contextMenuItems)
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/Base.py", line 114, in createListItem
                                                if checkBlacklist(bl_title):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/Base.py", line 123, in checkBlacklist
                                                addonUserDataFolder = xbmcvfs.translatePath("special://profile/addon_data/plugin.video.orftvthek")
                                              File "/storage/.kodi/addons/script.module.kodi-six/libs/kodi_six/utils.py", line 110, in __getattr__
                                                self._base_module, item
                                            AttributeError: Module <module 'xbmcvfs' (built-in)> does not have attribute "translatePath"!
                                            -->End of Python script error report<--
```

als Skin verwende ich Estuary, also der Standard bei dem's vorher ohne Probleme funktioniert hat =/

**Comment by s0faking** [comment]
da dürfte was mit der libreelec version nicht passen. welche version hast du denn installiert? hier hat jemand ein ähnliches problem https://github.com/CastagnaIT/plugin.video.netflix/issues/1145

**Comment by m3ltd0wn** [comment]
joa danke, hat sich nach dem Update auf Matrix erledigt >_< (sorry für's Zeit stehlen!)
