### ISSUE TITLE
Plugin Throws Exception during start up

### ISSUE THREAD

**Issue by BiMaKorn** [s0faking/plugin.video.orftvthek#143]
Hello, 

When starting the latest version of the plugin (1.0.2) the app is not starting, telling that further details can be found in the protocol.

In the log file I can see the following exception:

 ```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'Kodi' from 'kodi' (/usr/lib/python3.11/site-packages/kodi/__init__.pyc)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/default.py", line 4, in <module>
                                                       import addon
                                                     File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/addon.py", line 7, in <module>
                                                       from kodi import Kodi
                                                   ImportError: cannot import name 'Kodi' from 'kodi' (/usr/lib/python3.11/site-packages/kodi/__init__.pyc)
                                                   -->End of Python script error report<--
                                                   
2024-07-21 19:48:56.978 T:1280    debug <general>: onExecutionDone(8, /storage/.kodi/addons/plugin.video.orftvthek/resources/lib/default.py)

```

Further details:
Kodi 20.1 on Rasperry Pi 
 
I attached the log file
Greetings
[kodi.log](https://github.com/user-attachments/files/16325560/kodi.log)

**Comment by s0faking** [comment]
i'm not able to reproduce this. can you try to remove the addon completely and reinstall. did you install from the offical repo? if that doesn't work please enable debug logging and post the log file again

**Comment by s0faking** [comment]
closed due to inactivity
