### ISSUE TITLE
Date selection fails

### ISSUE THREAD

**Issue by luchmhor** [s0faking/plugin.video.orftvthek#26]
Selection of a Date in "Missed a Show" fails since today. Maybe they changed their urls?

`14:56:08 1988.247437 T:1486730144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: /schedule/10.10.2016
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 223, in <module>
                                                htmlScraper.openArchiv(link)
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 92, in openArchiv
                                                html = common.fetchPage({'link': url})
                                              File "/storage/.kodi/addons/script.module.parsedom/lib/CommonFunctions.py", line 435, in fetchPage
                                                con = urllib2.urlopen(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 423, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
                                            ValueError: unknown url type: /schedule/10.10.2016
                                            -->End of Python script error report<--
14:56:08 1988.337891 T:1874850720   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?banner=&link=%2Fschedule%2F10.10.2016&mode=getArchivDetail&backdrop=&title=Mo+-+10.10.2016`

**Comment by Rechi** [comment]
@luchmhor  I've made a PR to fix the issue.

**Comment by luchmhor** [comment]
the fix works perfectly for me on my libreelec raspberry, thx
