### ISSUE TITLE
Kodi 15.2: Plugin collides with YouTube?

### ISSUE THREAD

**Issue by killerbees19** [s0faking/plugin.video.orftvthek#72]
### Steps to reproduce
* Install Kodi 15.2 (i.e. from Ubuntu 16.04 repository)
* Install TVThek (0.8.5 or git-master) and YouTube (6.1.3) addons
* Open TVThek addon and try to play something

### Result without ServiceAPI
All menu lists (Shows, Live, …) are empty. No error in logfile.

### Result with ServiceAPI
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
               Error Type: <class 'urllib2.URLError'>
               Error Contents: <urlopen error [Errno 0] Error>
               Traceback (most recent call last):
                 File "/home/username/.kodi/addons/plugin.video.orftvthek/default.py", line 147, in <module>
                   scraper.getCategories()
                 File "/home/username/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py", line 137, in getCategories
                   response = self.__makeRequest(self.__urlShows)
                 File "/home/username/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py", line 371, in __makeRequest
                   return urllib2.urlopen(request) # nosec
                 File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                   return opener.open(url, data, timeout)
                 File "/usr/lib/python2.7/urllib2.py", line 429, in open
                   response = self._open(req, data)
                 File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                   '_open', req)
                 File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                   result = func(*args)
                 File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                   context=self._context)
                 File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                   raise URLError(err)
               URLError: <urlopen error [Errno 0] Error>
               -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getSendungen
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getSendungen) failed
```

### Workaround to fix it
* Uninstall YouTube addon
* Restart Kodi application
* Enjoy TVThek again…

I can't reproduce this issue on newer Kodi releases. I'm not a Python programmer and not familiar with Kodi plugin development. Maybe you know what's going wrong here?

**Comment by s0faking** [comment]
hm thats weird. what tells you that the addon collides with the youtube addon. i can't find anything that supports this thesis in your appended log. can you enable the debug log and post the output?

**Comment by killerbees19** [comment]
> what tells you that the addon collides with the youtube addon.

Only the fact, that it's reproducible.

I'll post the debug logs next week.

**Comment by s0faking** [comment]
please reopen the issue if this problem persists with 0.8.8
