### ISSUE TITLE
HTML Scraper & Progressive: Exception

### ISSUE THREAD

**Issue by killerbees19** [s0faking/plugin.video.orftvthek#73]
They changed something. It seems like there's no single MP4 file available anymore at the website?

```
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/user/.kodi/addons/plugin.video.orftvthek/default.py", line 126, in <module>
    playlist = scraper.getLinks(link,params.get('banner'),playlist)
  File "/home/user/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 405, in getLinks
    liz = self.html2ListItem(current_title,current_preview_img,"",current_desc,current_duration,'','',current_videourl, current_subtitles,False, True)
  File "/home/user/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 324, in html2ListItem
    return createListItem(title,banner,description,duration,date,channel,videourl,playable,folder, backdrop,self.pluginhandle,subtitles,blacklist,contextMenuItems)
  File "/home/user/.kodi/addons/plugin.video.orftvthek/resources/lib/base.py", line 63, in createListItem
    if videourl.lower().endswith('_qxb.mp4') or '_qxb' in videourl.lower():
AttributeError: 'bool' object has no attribute 'lower'                                                                                           
```

It runs properly with Service API enabled <b>or</b> with HLS stream method.

**Comment by s0faking** [comment]
jep i've seen that yesterday as well. they removed the progressive video sources from the website. probably because they use this stream protocol mostly for compatibility reasons (old apps or smart tv stuff). thats why the api still gets those links. i'll think of something to prevent people from choosing this settings combination (HTMLscraper+Progressive Setting) 

cheers,
s0fa

**Comment by s0faking** [comment]
4c54365 should fix the issue. i've added a new option "Enable Progressive Streaming Method". this option is only visible if you're using the serviceAPI Fetcher.
