### ISSUE TITLE
ORF-TVthek relaunch has broken the plugin

### ISSUE THREAD

**Issue by peletiah** [s0faking/plugin.video.orftvthek#80]
ORF-TVthek has been [completely overhauled and relaunched on Tuesday](https://der.orf.at/unternehmen/aktuell/tvthek-relaunch100.html), so the plugin is currently not working. Not sure how much it has changed, unfortunately I don't have the time to look into it myself right now. I get the following error right now:

> 18:57:27.956 T:1254093568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/default.py", line 154, in <module>
                                                scraper.getLiveStreams()
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 423, in getLiveStreams
                                                items = common.parseDOM(wrapper[0],name='li',attrs={'class': 'base_list_item.program.*?'})
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:57:28.093 T:1925900800   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getLive
18:57:28.094 T:1925900800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getLive) failed
18:57:43.291 T:1245704960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/default.py", line 154, in <module>
                                                scraper.getLiveStreams()
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 423, in getLiveStreams
                                                items = common.parseDOM(wrapper[0],name='li',attrs={'class': 'base_list_item.program.*?'})
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:57:43.421 T:1925900800   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getLive
18:57:43.422 T:1925900800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getLive) failed
19:21:09.379 T:1304425216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/default.py", line 154, in <module>
                                                scraper.getLiveStreams()
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 423, in getLiveStreams
                                                items = common.parseDOM(wrapper[0],name='li',attrs={'class': 'base_list_item.program.*?'})
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
19:21:09.508 T:1925900800   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getLive
19:21:09.509 T:1925900800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getLive) failed

**Comment by peletiah** [comment]
Sorry, my bugreport is a dupe of https://github.com/s0faking/plugin.video.orftvthek/issues/79
