### ISSUE TITLE
Unable to play live stream

### ISSUE THREAD

**Issue by raoulbhatia** [s0faking/plugin.video.orftvthek#95]
Worked 1-2 days back, doesnt work right now.

```
2020-03-15 12:34:16.193 T:18942   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'bool' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 142, in <module>
                                                scraper.getLiveStreams()
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 776, in getLiveStreams
                                                bundesland_title = bundesland_item.get('title')
                                            AttributeError: 'bool' object has no attribute 'get'
                                            -->End of Python script error report<--
2020-03-15 12:34:16.194 T:18942   DEBUG: onExecutionDone(31, /storage/.kodi/addons/plugin.video.orftvthek/default.py)
```

**Comment by s0faking** [comment]
the problem should be fixed. this only seems to happen when "bundesland heute" videos are available. i will try to push this to the official repo asap, considering the current situation here in austria

**Comment by s0faking** [comment]
i just realized the timestamp on your log. so probably the "bundesland heute" items aren't the main problem. the fix should work anyway but i will try to observe the issue for the next couple of days. probably some special markup on the website from all the "zib spezial" shows or something

**Comment by s0faking** [comment]
84c5141 should fix this error for real now ;)

**Comment by raoulbhatia** [comment]
Thanks for handling my report that swiftly!  I'll install from master and will report back.

**Comment by raoulbhatia** [comment]
I didn't see the issue happening again.  Closing this issue.

Thanks!
