### ISSUE TITLE
Kodi 19.0 Livestream not working with ServiceAPI enabled

### ISSUE THREAD

**Issue by kontaktwackler** [s0faking/plugin.video.orftvthek#98]
On Kodi 19.0 Matrix selecting the Livestream option when the ServiceAPI is enabled fails.
In the logs i can see the following

`2021-02-25 09:33:43.738 T:20126   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: append() takes exactly one argument (2 given)
                                                   Traceback (most recent call last):
                                                     File "/home/xxx/.kodi/addons/plugin.video.orftvthek/default.py", line 6, in <module>
                                                       Addon.run()
                                                     File "/home/xxx/.kodi/addons/plugin.video.orftvthek/resources/lib/Addon.py", line 137, in run
                                                       scraper.getLiveStreams()
                                                     File "/home/xxx/.kodi/addons/plugin.video.orftvthek/resources/lib/ServiceApi.py", line 304, in getLiveStreams
                                                       contextMenuItems.append(self.translation(30063), 'RunPlugin(plugin://%s/?mode=liveStreamRestart&link=%s)' % (xbmcaddon.Addon().getAddonInfo('id'), result.get('id')))
                                                   TypeError: append() takes exactly one argument (2 given)
                                                   -->End of Python script error report<--
                                                   
2021-02-25 09:33:43.738 T:20126   DEBUG <general>: onExecutionDone(3, /home/xxx/.kodi/addons/plugin.video.orftvthek/default.py)
2021-02-25 09:33:43.753 T:19997   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-02-25 09:33:43.765 T:20126    INFO <general>: Python interpreter stopped
2021-02-25 09:33:43.765 T:20126   DEBUG <general>: Thread LanguageInvoker 139674433590848 terminating
2021-02-25 09:33:43.785 T:20125   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getLive
2021-02-25 09:33:43.785 T:20125   DEBUG <general>: Thread waiting 139673745749568 terminating
2021-02-25 09:33:43.785 T:19997   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-02-25 09:33:43.785 T:19997   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getLive) failed
2021-02-25 09:33:43.785 T:19997   DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.orftvthek/)`

**Comment by s0faking** [comment]
should be fixed with the last commit

**Comment by kontaktwackler** [comment]
Thanks for the quick fix. Its working again
